### ISSUE TITLE
Broken images after updating to new build

### ISSUE THREAD

**Issue by mocknotes** [Rotonde/client#3]
In the README.md under the following:

- https://github.com/Rotonde/client#icon
- https://github.com/Rotonde/client#rich-content

It says to add images to the "/media/content/" folder but there is no media folder in the User repo. There's only a content folder.

I believe deleting "/media" in the entry.js file on line 38 may fix this issue or adding a media folder with a content sub folder in the User repo?

The user icon appears to map correctly without having a media folder.

**Comment by frozenpandaman** [comment]
Was just about to submit an issue for this. :) Seems when pointing to a file with `>>`, it's looking for images in `media/content/` while it should just be looking in `content/`. Drag-n-drop is also broken in that it won't copy images at all & insert the syntax into the status box (because `media/content/` doesn't exist).

**Comment by frozenpandaman** [comment]
We could fix https://github.com/Rotonde/beaker/issues/61 too (still present) by just converting spaces to underscores in filenames (i.e. disallowing spaces) – just add `.replace(" ","_")` after the three instances of `file.name` near the end of `scripts/operator.js`. Didn't want to put this in the PR though in case there's a better solution we want to implement instead.

**Comment by neauoire** [comment]
Merfed :)

**Comment by neauoire** [comment]
Fixed :)
